### ISSUE TITLE
Enhancement: Rotate volunteer images on home page

### ISSUE THREAD

**Issue by ogorman89** [codeforpdx/codepdx_website#105]
### Describe the Current Behavior/Feature:

- Make Flo and Hugh images static (Top two images)
- Rotate other members from the `volunteers` folder
<img width="1347" alt="Screenshot 2024-01-31 at 2 44 31 PM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/c3a41014-2a5b-47da-a9cd-914daaa97dae">

---

### Proposed Implementation:

Make a function that loads the bottom three images randomly.

**Comment by andycwilliams** [comment]
We could have those images change on every load, or have them fade in and out every so often (say ten seconds?). I like the latter.

**Comment by Jared-Krajewski** [comment]
> We could have those images change on every load, or have them fade in and out every so often (say ten seconds?). I like the latter.

change on load is fine. otherwise we have to stream additional images that most people will scroll past and not go back up to.

**Comment by andycwilliams** [comment]
Unassigning myself in the interest of not dragging this on even longer.

Anyone else feel free to assign yourself and take over my branch in the open PR.
