### ISSUE TITLE
Enhancement: Increase font size of Menu Items & Bold

### ISSUE THREAD

**Issue by nujabes77** [codeforpdx/codepdx_website#116]
### Describe the Current Behavior/Feature:

Increase font size of Menu Items & Bold

<img width="328" alt="Screenshot 2024-02-10 at 1 06 51 PM" src="https://github.com/codeforpdx/codepdx_website/assets/96148888/67bb87f6-8433-4342-8812-4deea9bab053">

**Comment by Jared-Krajewski** [comment]
their current size of `16px` or `1 rem` is standard nav bar text size (sometimes 14 is even use), what size would you like them to be?

**Comment by nujabes77** [comment]
Bigger!

Check out the website layout it’s tiny

**Comment by Jared-Krajewski** [comment]
<img width="440" alt="Screenshot 2024-02-12 at 12 42 56 PM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/4b0a524b-aeaf-4e0a-975a-c5f48bbd8b98">

heres our nav items along side another very popular civic tech groups nav items.

<img width="477" alt="Screenshot 2024-02-12 at 12 43 47 PM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/1a0eb464-08d1-47f1-b4af-e2e1d1deffbb">

heres our nav items next to discords website nav items.

If they are small for you it may be something your local text scaling? 

we can increase the font weight to 600 still as `home` appears in the last 2 screenshots. 

<img width="234" alt="Screenshot 2024-02-12 at 12 45 28 PM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/e68bb994-9607-415f-a637-7fe7f9f62ccf">


If contrast is the issue, we had been talking about possibly having to switch to the darker green that is used in some versions of our logo to help with contrast around the site.

<img width="159" alt="Screenshot 2024-02-12 at 12 54 34 PM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/d01fd044-1168-4c27-bf07-03c2dc87e634">

**Comment by nujabes77** [comment]
Change it to 600!

**Comment by andycwilliams** [comment]
This is what it looks like with font weight at 600. Right now it's applying to the CODE PDX title as well. I can exclude that but wanted to show what that looks like.

<img width="1045" alt="Capture" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/8d96fdf0-acfb-4f30-a649-29982cee557e">

**Comment by andycwilliams** [comment]
So are we decided on 600?

**Comment by Jared-Krajewski** [comment]
> So are we decided on 600?

yes, could try font 17 but 16 is larger standard size already. changes apply to nav links only.

**Comment by andycwilliams** [comment]
Two possibilities:

With `variant="h6"` and `component="p"`:
<img width="1044" alt="h6" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/23ab0b89-dda3-4f44-a020-f5f7abc73028">

With `fontSize={17}` & `fontWeight={600}`:
<img width="1043" alt="fontSizeAndWeight" src="https://github.com/codeforpdx/codepdx_website/assets/83156697/5c178ac0-0946-4236-9af5-fb04c87706ea">

**Comment by andycwilliams** [comment]
What's the current status for this issue?

**Comment by Jared-Krajewski** [comment]
font weight to 600 and leave size at 1 rem (16px) for only the 3 nav links to match what the rest of the world does.
