### ISSUE TITLE
Enhancement: Fix Links

### ISSUE THREAD

**Issue by nujabes77** [codeforpdx/codepdx_website#118]
### Describe the Current Behavior/Feature:

On project the following links don't work

Recordsponge:
Website link
Discord - Invalid Invite

PASS:
Discord - Invalid Invite

Code PDX
Remove website icon. Just pointing back to the website - doesn't make sense

**Comment by andycwilliams** [comment]
I believe the Discord invites expire after a while. Is it possible to get permanent ones?

**Comment by nujabes77** [comment]
https://discord.gg/W86M8u9wB2

this one will never expire

**Comment by Jared-Krajewski** [comment]
Those discord links were permanent channel invites to the server that then direct to the specific channel, due to changes in server configs they broke. 

Maybe this section actually needs a refactor to just remove all of the Icons under the image and just place the GH one next to the projects title.

**Comment by andycwilliams** [comment]
I think removing all but the GitHub links may be the way to go. I don't know how critical it is to have the links to specific channels, especially since we already link to the Discord itself

**Comment by asaltveit** [comment]
Also, all four links in the footer currently just create a new tab of the page that the user was on (whether the page is projects/home/etc.).

**Comment by andycwilliams** [comment]
Yes that's specified in issue #82

**Comment by JaeGif** [comment]
I'm new to CodePDX, this seems like a great first issue to get used to the workflow. Is there a contributing guide anywhere I can read, or can I just assign myself to this issue?

Edit: found the contributing guide.

**Comment by JaeGif** [comment]
Following the discussion here, I feel the best course of action is to remove the individual channel discord links. The volunteer section already has links to the discord, and the footer has a link as well.

**Comment by Jared-Krajewski** [comment]
> Following the discussion here, I feel the best course of action is to remove the individual channel discord links. The volunteer section already has links to the discord, and the footer has a link as well.

I am good with removing the discord links.
