### ISSUE TITLE
[Feature Request] - Tim requests blog feature

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/codepdx_website#129]
### Feature Description:
Quick blog options using Markdown files.

### Problem it Solves:
? Tim requested.

### Proposed Solution:
Tim requests just something using Markdown files, so easy to writeup and load.

### Alternatives Considered:
A clear and concise description of any alternative solutions or features you've considered and why they could or could not work.

**Comment by andycwilliams** [comment]
@ogorman89 What were your ideas for the blogging tools to use again?

**Comment by Jared-Krajewski** [comment]
we had previously proposed this idea and it was shot down because of necessity to maintain amongst volunteers and lapse in posts appear as an inactive organization. I personally am not opposed to it and think it could be a great way to communicate our achievements, updates, events, ect..

**Comment by andycwilliams** [comment]
Is there a way to import LinkedIn posts?

**Comment by Jared-Krajewski** [comment]
> Is there a way to import LinkedIn posts?

possibly

https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/posts-api?view=li-lms-2024-02&tabs=http

**Comment by Jared-Krajewski** [comment]
Closing this issue, we will likely not be able to effectively maintain this feature if implemented. If things change we can create a new one in the same spirit.
