### ISSUE TITLE
Enhancement: finish dark mode theme

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/codepdx_website#22]
### Describe the Current Behavior/Feature:

This issue will need nav bar merged in first to update supporting code. 

With the nav bar is a dark mode toggle. Right now there is basically enough of a dark mode theme to test that it was set up properly. Needs a full dark mode theme using [MUI dark mode colors] (https://mui.com/material-ui/customization/dark-mode/).  

### Proposed Implementation:

All of the magic goes in theme.js

**Comment by xscottxbrownx** [comment]
I also propose to research how to start the toggle based on the user's system preferences...  

So if their system is set to dark mode, start in dark mode.

**Comment by andycwilliams** [comment]
> I also propose to research how to start the toggle based on the user's system preferences...
> 
> So if their system is set to dark mode, start in dark mode.

I found this: 

```
const useThemeDetector = () => {
    const getCurrentTheme = () => window.matchMedia("(prefers-color-scheme: dark)").matches;
    const [isDarkTheme, setIsDarkTheme] = useState(getCurrentTheme());  
    const mqListener = (e => {
        setIsDarkTheme(e.matches);
    });
    
    useEffect(() => {
      const darkThemeMq = window.matchMedia("(prefers-color-scheme: dark)");
      darkThemeMq.addListener(mqListener);
      return () => darkThemeMq.removeListener(mqListener);
    }, []);
    return isDarkTheme;
}
```

From here

https://medium.com/hypersphere-codes/detecting-system-theme-in-javascript-css-react-f6b961916d48

**Comment by andycwilliams** [comment]
Have we determined whether this is part of MVP? I'd really like it to be but don't necessarily believe it's essential, at least not since we're aiming to wrap things up soon.

I'm willing to take it up if nobody else is but also want to say that I'm already assigned to a handful of other things. So it'd likely take a little while before I could start. 

If someone else can work on this sooner that'd be awesome.

**Comment by nonotnoah** [comment]
> If someone else can work on this sooner that'd be awesome.

I'd be happy to help with this. I've started a branch following MUI's dark mode implementation. I have the system theme preference detection and theme contexts set up.

I noticed there are a bunch of different ways this project is styled, and I was hoping someone could talk me through the differences before I step on any toes.

**Comment by Jared-Krajewski** [comment]
> > If someone else can work on this sooner that'd be awesome.
> 
> I'd be happy to help with this. I've started a branch following MUI's dark mode implementation. I have the system theme preference detection and theme contexts set up.
> 
> I noticed there are a bunch of different ways this project is styled, and I was hoping someone could talk me through the differences before I step on any toes.

@nonotnoah you can take this on if youd like. @andycwilliams I would polish off the other stuff you started before biting off any more tasks. no need to swamp yourself.

**Comment by andycwilliams** [comment]
Is this a feature we want finished by the end of the month? There isn't a ton of time if so. Depends on how much progress has been made.

**Comment by Jared-Krajewski** [comment]
> Is this a feature we want finished by the end of the month? There isn't a ton of time if so. Depends on how much progress has been made.

This can be added whenever, not a priority to put the website online so progress can continue on this as Noah has time. If its not ready I will just comment out the toggle and it can start out without dark mode.

**Comment by bernardthered** [comment]
@nonotnoah - I'm thinking about picking this up, but let me know if you still want to work on it and I can pick up a different issue no problem. Or if you have a branch started with some commits, you can point me at that and I can take it from there.

**Comment by nonotnoah** [comment]
Hey Bernard, feel free to take it over!

**Comment by andycwilliams** [comment]
Hello @bernardthered, are you still interested?

**Comment by kimmykokonut** [comment]
i may be interested if @bernardthered is not.

**Comment by bernardthered** [comment]
A bunch of life stuff came up for me after the last work session I went to. Others are welcome to pick this one up!

**Comment by JaeGif** [comment]
I'll take this one on. Is there a button/UI already decided on for the toggle? And or is there a Figma or design document to reference for the colors and contrasts? Or are we just using the MUI default dark mode scheme?

Edit: 🤦 I found the figma board. I'll work on my reading skills haha

**Comment by Jared-Krajewski** [comment]
> I'll take this one on. Is there a button/UI already decided on for the toggle? And or is there a Figma or design document to reference for the colors and contrasts? Or are we just using the MUI default dark mode scheme?
> 
> Edit: 🤦 I found the figma board. I'll work on my reading skills haha

The button is existing and commented out in `Navbar.jsx`, it's connected to a mostly empty theme (was set up for testing the button). Most of the commented code in that file will need to be uncommented for it to work. The plan was to just use MUI default. I started to do a dark mode in Figma but it would have been faster for me to just do the actual code than finish it in Figma so I would say to mostly ignore what you see in there.  

If you need me for anything on this msg me on discord, my name is the same on there. I see messages on there a lot faster so you will most likely get a quicker response than on here since this will likely need some new contrasting icons and other assets (unless you are comfortable making them yourself)

<img width="241" alt="Screenshot 2024-04-15 at 10 13 01 AM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/1235cabb-39e1-4bee-b0a8-395ae3ab75f5">
