### ISSUE TITLE
Image size optimization

### ISSUE THREAD

**Issue by ogorman89** [codeforpdx/codepdx_website#56]
### Describe the Current Behavior/Feature:

- Render the smallest possible image for each viewpoint
- Two versions of each image, break on 
- Webp conversions for all jpgs

---

### Proposed Implementation:

- in assets create desktop and mobile folders

**Comment by andycwilliams** [comment]
Is this still planned? At least for MVP?

**Comment by Jared-Krajewski** [comment]
yes
