### ISSUE TITLE
Hero Styling Enhancements

### ISSUE THREAD

**Issue by ogorman89** [codeforpdx/codepdx_website#58]
### Describe the Current Behavior/Feature:

- remove button from hero

---

**Comment by andycwilliams** [comment]
Is removing the button really the only change we need?

If so, I can maybe resolve this at the same time as #54.

**Comment by andycwilliams** [comment]
Requesting confirmation whether removing the hero button is the only requirement for this issue.

**Comment by andycwilliams** [comment]
This will be resolved once PR 72 is merged
