### ISSUE TITLE
Events Section Styling Enhacements

### ISSUE THREAD

**Issue by ogorman89** [codeforpdx/codepdx_website#63]
### Describe the Current Behavior/Feature:

 - Events cards full-width center on mobile
 - Center text on mobile
 - Adjust google calendar to scale better (make it fluid but keep aspect ratio)

Currently.. 
<img width="398" alt="Screenshot 2024-01-30 at 7 43 40 PM" src="https://github.com/codeforpdx/codepdx_website/assets/114430929/46648d09-210a-44a4-b19c-60474c1de0e6">

https://github.com/codeforpdx/codepdx_website/assets/114430929/46a9448b-9a7c-47cb-b39b-973770101ddd

---

### Proposed Implementation:

- Center boxes in mobile view only and allow text to take up more screen space. 
- Potentially use % units to scale the calendar and remove the breakpoints.

**Comment by fighawkins** [comment]
I am working on this issue and will be submitting a pull request soon
