### ISSUE TITLE
Projects Section Styling Enhacement

### ISSUE THREAD

**Issue by ogorman89** [codeforpdx/codepdx_website#64]
### Describe the Current Behavior/Feature:

- Cards should all be the same min-height
- Reduce padding below logos and text
- Change codePDX logo to new SVG with CODE PDX
- Make a clearer SVG of the PASS logo

---

**Comment by Jared-Krajewski** [comment]
made a push to center text, originally was just going to be for mobile but I think it looks better in all views in the cards. If you are ready this can be merged and the Image changes will come later on since I don't have time to try and make new images.
