### ISSUE TITLE
Bug: Tests are not well encapsulated/are not cleaned up after completion

### ISSUE THREAD

**Issue by milofultz** [codeforpdx/codepdx_website#75]
When adding tests, calls to `window.matchMedia` bleed over to all following tests within a file. Each test should be isolated to itself to ensure that the tests are consistent and not affected by unrelated tests or tests in close proximity.

---

### Reproduction Steps:

1. Run a test on `test/components/NavBar/NavMenu.test.jsx`. See that it passes.
1. In `test/components/NavBar/NavMenu.test.jsx`, move the test named `it('renders contacts and civic profile links below 600px'` above `it('does not render contacts and civic profile links above 600px'`.
1. Run the test on `test/components/NavBar/NavMenu.test.jsx` again. See that it fails.

---

### Expected Behavior:

The tests should not change their outcomes based on functions/behavior in unrelated tests.

---

### Actual Behavior:

Functions/behavior in tests affect other unrelated tests.

---

### Possible Solution (optional):

1. Implement an `afterEach` in a [vitest setups file](https://vitest.dev/config/#setupfiles) that handles a resetting of `window.matchMedia`.
2. Other tests with complex and/or global modifications should be examined to ensure their behaviors are isolated.

**Comment by xscottxbrownx** [comment]
@milofultz I think this issue, and your other new one are in the wrong repo.

I believe you meant for these to be in the PASS repo.

**Comment by xscottxbrownx** [comment]
This is not for this repo. I believe it is for PASS.

**Comment by milofultz** [comment]
Ack, sorry! Totally missed the first message. You are correct this and the other one are for PASS. I’ll reopen this there, thank you!
