### ISSUE TITLE
Enhancement: CODE PDX logo contrast

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/codepdx_website#80]
### Describe the Current Behavior/Feature:

CODE PDX logo in Navbar and Footer don't have enough contrast at some viewports either due to blobs rendering or not, OR light mode vs dark mode.

---

### Proposed Implementation:

Maybe just functionally determining the src file of the image based on conditions?

---

<img width="527" alt="Screenshot 2023-12-27 at 8 03 35 AM" src="https://github.com/codeforpdx/codepdx_website/assets/71395931/07825aaf-b2cd-44e1-a5f5-75857e72150b">
<img width="648" alt="Screenshot 2023-12-27 at 8 03 54 AM" src="https://github.com/codeforpdx/codepdx_website/assets/71395931/a9b0ed52-6628-486b-ae62-998d69f5a0c5">
<img width="1440" alt="Screenshot 2023-12-27 at 8 04 06 AM" src="https://github.com/codeforpdx/codepdx_website/assets/71395931/a4439822-86d6-42f8-93e0-199dbdc129c2">

**Comment by andycwilliams** [comment]
Having it just use a different, better contrasting image depending on specific conditions seems like the simplest solution.

I don't know enough about branding or UX to say whether it's important that logos be completely uniform (i.e. the exact same colors and everything no matter the conditions). But I don't think just changing the hue really hurts the "brand" that much.

Especially if that's what we're going to do with dark mode anyway. Not sure what the plan is with that.

**Comment by Jared-Krajewski** [comment]
This will be fixed as part of the issue I have for the nav and footer. It was originally white and worked fine but we were asked to change the color.

**Comment by xscottxbrownx** [comment]
> This will be fixed as part of the issue I have for the nav and footer. It was originally white and worked fine but we were asked to change the color.

ahhh didn't realize.  Want me to make issue for footer and delete this one?

**Comment by xscottxbrownx** [comment]
@Jared-Krajewski 

It's not perfect, but I have this (as I was working on it before your comment.)

I also didn't see any footer issue, so not sure if there's anything else to fix there (besides the links.)

Let me know your thoughts.  Could delete this issue/approach entirely. Could review this and push this change, then just edit the Navbar issue to not include this piece of it. etc.

https://github.com/codeforpdx/codepdx_website/assets/71395931/da0a2f0c-5a01-4138-b892-6b181f9619fa

**Comment by Jared-Krajewski** [comment]
> @Jared-Krajewski
> 
> It's not perfect, but I have this (as I was working on it before your comment.)
> 
> I also didn't see any footer issue, so not sure if there's anything else to fix there (besides the links.)
> 
> Let me know your thoughts. Could delete this issue/approach entirely. Could review this and push this change, then just edit the Navbar issue to not include this piece of it. etc.
> 
>  Screen.Recording.2023-12-28.at.8.17.19.AM.mov


I didn't notice but I guess it wasn't actually added as an issue. It just vaguely says contrast but thats what it was referring to. The logo and CODE PDX text need to be updated for both. I'm ok with these changes and can work from there.

**Comment by Jared-Krajewski** [comment]
This issue was resolved, not sure when but logos were changed to white to help with contrast. Will re open a new issue if other changes are needed.
