### ISSUE TITLE
Enhancement: Vite XSS Vulnerability

### ISSUE THREAD

**Issue by ogorman89** [codeforpdx/codepdx_website#87]
### Describe the Current Behavior/Feature:

![Screen Shot 2024-01-03 at 2 06 13 PM](https://github.com/codeforpdx/codepdx_website/assets/3335277/b4223dd9-6d3f-4b88-b371-8b4e5d39d876)

Update Vite version to close XSS vulnerability recorded in the last npm audit run.

---

### Proposed Implementation:

npm audit fix 😎

**Comment by andycwilliams** [comment]
I noticed that vite is listed in both `dependencies` and `devDependencies`. Isn't this redundant?
