### ISSUE TITLE
Create Events section of homepage

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/codepdx_website#9]
### Figma link for component:
[Events section of homepage](https://www.figma.com/file/QWycOkxNJmtiyZ3v8imIzx/Code-PDX-website?type=design&node-id=0-845&mode=design&t=JhDPDVeP1SwPMWwa-4)

---
### Feature Description:
Create Upcoming Events section of homepage containing:
- Header text
- Divs/Boxs/Containers of paragraph text
- Integrate a Google calendar (embed/iframe/etc)

---
### Screenshots (if applicable):
<img width="801" alt="Screenshot 2023-10-04 at 8 38 16 PM" src="https://github.com/codeforpdx/codepdx_website/assets/71395931/bb0740f1-41e2-4924-a359-8f5b6d02e6b3">

**Comment by Jared-Krajewski** [comment]
Likely Scott and I will do this because I need to integrate the google calendar with API token.
