### ISSUE TITLE
Enhancement: Adjustments for initial deployment

### ISSUE THREAD

**Issue by ogorman89** [codeforpdx/codepdx_website#93]
### Describe the Current Behavior/Feature:

This issue is a collection of small adjustments needed so we can get the initial site hosted.

---

### Proposed Implementation:

Per @Jared-Krajewski :
- remove the tags that house the logo. I was just going to comment them out so they can get tuned in the future
- remove Epicodus from `secondarySponsors`
- comment out the dark mode toggle until it is ready
- add "Home" to `navbar`

**Comment by andycwilliams** [comment]
This is probably a good issue to include replacing the EmailJS keys. I'm setting up a new account just for CODE PDX and can get those made soon.
